field: 6d547dab-3d15-44cf-9ee2-2d46f37db6ce # Classes Slides
fieldLayouts:
  28eeca9b-c454-4b30-87c5-65246e4d0c1f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b0bc9f09-62f0-4eb2-807f-395e29fdc51d # Classes Slide Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4681a7a5-aaa5-406f-a374-fafa7e664994
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 03362b47-11fb-4022-8604-e324d8bc0137 # Classes Slide Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5711802-0c5f-4465-bbf0-33343d5b8ed3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2b0cf0b7-8482-4c37-b48b-472c7277cf6f # Classes Slide Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cea97e44-d8bd-4de3-801a-d411e8848ce5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f3020da7-9b25-4fe6-b869-b7c92718a072
        userCondition: null
fields:
  2b0cf0b7-8482-4c37-b48b-472c7277cf6f: # Classes Slide Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: homeClassesSlideImage
    instructions: null
    name: 'Classes Slide Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:14a6f0f3-b531-4d1d-a2b5-c9b0a56a2ef0' # Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:14a6f0f3-b531-4d1d-a2b5-c9b0a56a2ef0' # Assets
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:14a6f0f3-b531-4d1d-a2b5-c9b0a56a2ef0' # Assets
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  03362b47-11fb-4022-8604-e324d8bc0137: # Classes Slide Description
    columnSuffix: clxmwbgj
    contentColumnType: text
    fieldGroup: null
    handle: homeClassesSlideDescription
    instructions: null
    name: 'Classes Slide Description'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  b0bc9f09-62f0-4eb2-807f-395e29fdc51d: # Classes Slide Title
    columnSuffix: zwiayzry
    contentColumnType: text
    fieldGroup: null
    handle: homeClassesSlideTitle
    instructions: null
    name: 'Classes Slide Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: homeClassesSlide
name: 'Classes Slide'
sortOrder: 1
