field: b366fef5-3588-46c2-8d62-354769fb5cec # Philosophy List
fieldLayouts:
  33c86740-572e-453b-967c-0a5069bd1ab1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5b538405-4604-4935-95ad-c4f6cb5da0b5 # Philosophy Item Head
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65ff3300-9829-460a-8c1d-6e028ca03dbb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cf1c4053-2810-40b9-8b64-e0031fbd8588 # Philosophy Item Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 703d2043-91b0-4315-a2c3-275bebade4e5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 265529ee-d1b6-4f49-b462-20a2222ae08c
        userCondition: null
fields:
  5b538405-4604-4935-95ad-c4f6cb5da0b5: # Philosophy Item Head
    columnSuffix: bgmgmqjp
    contentColumnType: text
    fieldGroup: null
    handle: homePhilosophyItemHead
    instructions: null
    name: 'Philosophy Item Head'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cf1c4053-2810-40b9-8b64-e0031fbd8588: # Philosophy Item Description
    columnSuffix: wuocjosm
    contentColumnType: text
    fieldGroup: null
    handle: homePhilosophyItemDescription
    instructions: null
    name: 'Philosophy Item Description'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: homePhilosophyItem
name: 'Philosophy Item'
sortOrder: 1
