field: 6ed75db1-ad9e-4521-9601-42a5208aca06 # Difference List
fieldLayouts:
  dc2e2101-acfd-4e8a-a2e3-04664294ad06:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e01ee6f5-d97e-41c1-90aa-6bfa688644de # Difference Item Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5fcfea8-ae5d-443a-9583-e407ca2e9220
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dc3c592a-a80a-4b90-82de-2ef042f17c7d # Difference Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2648f9a-4ff2-4264-a3e2-62df1d1c3d64
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3faad3b2-404b-43cd-86a5-922b8590def5
        userCondition: null
fields:
  dc3c592a-a80a-4b90-82de-2ef042f17c7d: # Difference Text
    columnSuffix: whdbgzfo
    contentColumnType: text
    fieldGroup: null
    handle: homeDifferenceText
    instructions: null
    name: 'Difference Text'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  e01ee6f5-d97e-41c1-90aa-6bfa688644de: # Difference Item Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: homeDifferenceItemIcon
    instructions: null
    name: 'Difference Item Icon'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:14a6f0f3-b531-4d1d-a2b5-c9b0a56a2ef0' # Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:14a6f0f3-b531-4d1d-a2b5-c9b0a56a2ef0' # Assets
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: homeDifferenceItem
name: 'Difference Item'
sortOrder: 1
