fieldLayouts:
  8e9af423-60a8-4a96-b5f2-35786da806c4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 54096a27-1372-421e-b700-efac78b55897
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dbb53240-67f6-4afe-97f7-2bf4896df125
        userCondition: null
handle: podcasts
hasTitleField: true
name: Podcasts
section: f298ea40-4b97-45ea-9487-8bde6bb0540e # Podcasts
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
