fieldLayouts:
  6993ca9b-d878-41e4-9233-46b20e8dfed4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1195015a-5ee9-40c7-9f4d-a41942465afc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee757f8e-ee65-4f02-8c69-eb90acbd9dbb # Podcast Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 152c4667-d321-4b51-9fdc-8523d0628ece
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 669c6ed2-f83d-4272-900e-a301c802839a # Podcast Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b6f7170-fe8a-4275-a410-672a44e23137
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f2f30c2d-3302-48f9-ab43-2fe10d21e800 # Podcast Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a88ad9c5-7bcf-4a25-9bb9-1467b0e08164
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7423b0a5-5fd4-453c-bf35-2239363d4c5a # Podcast Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb0f66a8-c9ca-497e-aec3-22f490f0078c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eb3e9070-3281-4a39-b619-956f9f2b1925 # Podcast Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11de27d0-4224-48c5-a073-055a8d36c440
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e6f60306-b1b8-4c4f-a1f3-6cb6827ccf35
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ec86547a-843d-4f8f-b33c-e98741f534ec # Podcast Apple URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8639a416-d6fc-44f3-a0da-c97f37b1a9e1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b9670d0b-5a81-4f60-b60d-718a73dd81b5 # Podcast Spotify URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbf276a0-a3f5-4559-990c-2c5188482871
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3535db6f-4eec-4e4f-9099-c45146b30d88 # Podcast YouTube Embed URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e53e9268-34ea-4926-b7cf-a44a19f6d642
            userCondition: null
            warning: null
            width: 100
        name: URLs
        uid: 13774c88-de77-4fb1-9b63-8ce3a2de09fc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 14f5726b-60c3-4f4e-bc91-c2b2e0364c3d # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb00205a-33d5-46b6-988b-8e6b2cbecd7a
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: d959d2dc-9e64-46c4-a782-48c54f8ee9b1
        userCondition: null
handle: podcast
hasTitleField: true
name: Podcast
section: 72019b80-1d51-41ee-a5ba-74053c9a5bd0 # Podcast Episode
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
