fieldLayouts:
  dcbb6f51-6abd-4ea7-befa-63746f51e6f3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 66a6f730-63f8-458e-a54d-d04b85d0defa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 03ca5c96-0536-4845-9b34-97eb57f9e59a # Testimonial Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9bb9a39-9e13-4853-9447-026abf4a3d42
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4baabcc-a917-427c-92e1-321c37f3b023 # Testimonial Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e9916a4-dd1f-424f-9b41-b58ef979d356
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 94fe934d-aa00-4e85-8166-32544da517f8
        userCondition: null
handle: testimonials
hasTitleField: false
name: Testimonials
section: 76361647-45f5-4715-8354-8155fe5b6810 # Testimonials
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
