columnSuffix: letqbsic
contentColumnType: text
fieldGroup: d6e77677-670a-4b49-a894-c4d43cf36dac # About
handle: aboutMbCopy
instructions: null
name: 'About MB Copy'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: f062b6d8-1aff-4ec3-bef3-e9a7f786c1fc # Simple
  columnType: text
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
