columnSuffix: knwmdeat
contentColumnType: text
fieldGroup: d6e77677-670a-4b49-a894-c4d43cf36dac # About
handle: aboutClassListHead
instructions: null
name: 'Class List Head'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
