columnSuffix: null
contentColumnType: string
handle: aboutClassList
instructions: null
name: 'Class List'
searchable: false
settings:
  entryTypes:
    -
      uid: 830bfd32-7cb9-4f3f-925d-05f0ff7b6562
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
