columnSuffix: null
contentColumnType: string
handle: aboutMbSidebarAccordion
instructions: null
name: 'Sidebar Accordion'
searchable: false
settings:
  entryTypes:
    -
      uid: ae634bf8-48e5-4164-8ab4-7ea661caa5a5
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
