columnSuffix: srulqscd
contentColumnType: text
fieldGroup: ec6b8c17-c1c6-4f35-ad4c-eb15724fdc38 # About Aly
handle: aboutAlyCredentials
instructions: null
name: Credentials
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: f062b6d8-1aff-4ec3-bef3-e9a7f786c1fc # Simple
  columnType: text
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
