columnSuffix: sfdvwwid
contentColumnType: text
fieldGroup: 77517042-ad23-4cb1-a85b-a749aad0e660 # Blog
handle: blogTitle
instructions: null
name: title
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: f062b6d8-1aff-4ec3-bef3-e9a7f786c1fc # Simple
  columnType: text
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
