columnSuffix: null
contentColumnType: string
handle: classesList
instructions: null
name: 'Class List'
searchable: false
settings:
  entryTypes:
    -
      uid: 84d4713f-9e53-4b1c-8d8e-e5600fa07269
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
