columnSuffix: null
contentColumnType: string
handle: faqs
instructions: null
name: FAQs
searchable: false
settings:
  entryTypes:
    -
      uid: aa2ff4ae-da1b-4ca0-8b78-03ce349ee782
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
