columnSuffix: null
contentColumnType: string
handle: homeDifferenceList
instructions: null
name: 'Difference List'
searchable: false
settings:
  entryTypes:
    -
      uid: 20b6bb8e-2942-4e94-aed6-92a7f8b48e54
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
