columnSuffix: knwmdeat
contentColumnType: text
fieldGroup: 07dede5f-e375-4ca2-9622-0adde621a5c3 # Home
handle: homeClassListHead
instructions: null
name: 'Class List Head'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
