columnSuffix: null
contentColumnType: string
fieldGroup: 07dede5f-e375-4ca2-9622-0adde621a5c3 # Home
handle: homePhilosophyList
instructions: null
name: 'Philosophy List'
searchable: false
settings:
  contentTable: '{{%matrixcontent_homephilosophylist}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
