columnSuffix: null
contentColumnType: string
handle: homeProductsList
instructions: null
name: 'Products List'
searchable: false
settings:
  entryTypes:
    -
      uid: 8fcc0341-0be2-48bb-867d-c746a78e9c82
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
