columnSuffix: null
contentColumnType: string
handle: homeMembershipOptions
instructions: null
name: 'Membership Options'
searchable: false
settings:
  entryTypes:
    -
      uid: af23db4e-b155-44e8-9387-875605aafbcc
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
