columnSuffix: null
contentColumnType: string(255)
fieldGroup: 07dede5f-e375-4ca2-9622-0adde621a5c3 # Home
handle: homeApproachCta
instructions: null
name: 'Approach CTA'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
