columnSuffix: null
contentColumnType: string
handle: homeClassesSlides
instructions: null
name: 'Classes Slides'
searchable: false
settings:
  entryTypes:
    -
      uid: 4e1b233a-aa11-4a04-b275-28c79544d66a
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
