columnSuffix: null
contentColumnType: string(255)
handle: homeTryCta
instructions: null
name: 'Try CTA'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
