columnSuffix: null
contentColumnType: string
handle: homeFaqList
instructions: null
name: 'FAQ List'
searchable: false
settings:
  entryTypes:
    -
      uid: 449581e6-e2e9-4598-94f7-9baec2081577
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
