columnSuffix: null
contentColumnType: string
handle: homeCompanyBullets
instructions: null
name: 'Company Bullets'
searchable: false
settings:
  entryTypes:
    -
      uid: 21b6ca88-6ace-44d7-8c0e-fb6ccbab53d8
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
