columnSuffix: null
contentColumnType: string
handle: homeTestimonialsList
instructions: null
name: 'Testimonials List'
searchable: false
settings:
  entryTypes:
    -
      uid: f851a4be-7bd7-4309-b0ef-c6ae24caecf3
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
