columnSuffix: null
contentColumnType: string
handle: homePhilosophyList
instructions: null
name: 'Philosophy List'
searchable: false
settings:
  entryTypes:
    -
      uid: b570e17c-b9e6-413f-bebf-b38f5c0f529d
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
