columnSuffix: kpsaehej
handle: homeProductLink
instructions: null
name: 'Products List - Products Items - Product Link'
searchable: false
settings:
  fullGraphqlData: false
  maxLength: 255
  showLabelField: false
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
