columnSuffix: fzcpzdxo
contentColumnType: text
fieldGroup: 1048f1f6-9ff4-4134-94d1-1dc90d85b12c # Podcasts
handle: podcastYoutubeEmbedUrl
instructions: null
name: 'Podcast YouTube Embed URL'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
