columnSuffix: ftsdbrcc
contentColumnType: string(255)
handle: podcastUrl
instructions: null
name: 'Podcast URL'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
