columnSuffix: ewnczxrn
contentColumnType: string(255)
handle: podcastYoutubeUrl
instructions: null
name: 'Podcast YouTube URL'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
