columnSuffix: ftsdbrcc
contentColumnType: string(255)
fieldGroup: 1048f1f6-9ff4-4134-94d1-1dc90d85b12c # Podcasts
handle: podcastUrl
instructions: null
name: 'Podcast URL'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
