columnSuffix: wltovyby
contentColumnType: string(255)
handle: podcastAppleUrl
instructions: null
name: 'Podcast Apple URL'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
