columnSuffix: ahnpbrql
contentColumnType: text
fieldGroup: e528c06e-6a42-4282-ae2b-4e38fceda003 # Testimonials
handle: testimonialIntro
instructions: null
name: 'Testimonial Intro'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: f062b6d8-1aff-4ec3-bef3-e9a7f786c1fc # Simple
  columnType: text
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
