columnSuffix: null
contentColumnType: string
handle: testimonialItems
instructions: null
name: 'Testimonial Items'
searchable: false
settings:
  entryTypes:
    -
      uid: dccb8fdf-e43a-4604-838c-f3e8f9568225
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
