columnSuffix: nsgrmijx
contentColumnType: string(255)
handle: tikTok
instructions: null
name: 'Tik Tok'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
