columnSuffix: kywzrjom
contentColumnType: string(255)
handle: youTube
instructions: null
name: YouTube
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
