defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c817d89d-53c9-4fc0-957d-f3a0de39fb06 # About Modern Body
handle: aboutModernBody
maxAuthors: 1
name: 'About Modern Body'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  9d74e71c-d037-432d-887d-4065ec79a9c7: # Modern Body
    enabledByDefault: true
    hasUrls: true
    template: aboutMB/_entry.html
    uriFormat: about-modern-body
type: single
