defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1f1a8a59-4979-401d-82a3-b9b53b9c1de2 # Classes
handle: classes
maxAuthors: 1
name: Classes
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  9d74e71c-d037-432d-887d-4065ec79a9c7: # Modern Body
    enabledByDefault: true
    hasUrls: true
    template: classes/_entry.html
    uriFormat: classes
type: single
