defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: ac16953e-d476-4c04-a41e-9115e69331e6 # Contact
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  9d74e71c-d037-432d-887d-4065ec79a9c7: # Modern Body
    enabledByDefault: true
    hasUrls: true
    template: contact/_entry
    uriFormat: contact
type: single
