defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6dd9aa0b-b4f3-4320-8d34-181a52eb6a00 # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  9d74e71c-d037-432d-887d-4065ec79a9c7: # Modern Body
    enabledByDefault: true
    hasUrls: true
    template: home/_entry
    uriFormat: __home__
type: single
