defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6c3a246e-c9d3-4dc1-86f1-3f3193836374 # Podcasts
handle: podcasts
maxAuthors: 1
name: Podcasts
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  9d74e71c-d037-432d-887d-4065ec79a9c7: # Modern Body
    enabledByDefault: true
    hasUrls: true
    template: podcasts/_entry
    uriFormat: podcasts
type: single
